[build]
  command = "npm install && npm run build"
  functions = "netlify/functions"

[[redirects]]
  from = "/apply"
  to = "/apply.html"
  status = 200
  force = true

[[redirects]]
  from = "/apply/"
  to = "/apply.html"
  status = 200
  force = true

[[redirects]]
  from = "/login"
  to = "/login.html"
  status = 200
  force = true

[[redirects]]
  from = "/login/"
  to = "/login.html"
  status = 200
  force = true

[[redirects]]
  from = "/portal"
  to = "/portal.html"
  status = 200
  force = true

[[redirects]]
  from = "/portal/"
  to = "/portal.html"
  status = 200
  force = true
